### ISSUE TITLE
The memory range of marked pointers

### ISSUE THREAD

**Issue by haozheshz** [EMarci15/asplos22-minesweeper-reproduce#1]
Hi there,
Thanks a lot for your impressive work. I came across a problem while reading your code and I was hoping you could assist me. Specifically, in the ```markItemsContaining()``` function which I list below, I noticed that only pointers point to the heap will be marked in the shadow space because ```min_entry``` and ```max_entry``` point to the start and end address of the heap respectively.  However, given that jemalloc uses ```mmap()``` to map new pages to the memory ranges between the heap and stack, blocks allocated from the ```mmap()``` region may be freed even if they have dangling pointers point to them. I was wondering if you had taken this into account and if so, how it is handled. Thank you for your time and expertise. And here's the function. It is defined in the header file ```central_quarantine.h```.
```
 inline void CentralQuarantine::markItemsContaining(void *ptr, void *min_entry, void *max_entry) {
    // Only mark if within range of ptrs in quarantine
    if ((ptr >= min_entry) && (ptr < max_entry))
        shadow.mark(ptr);
}
```

**Comment by EMarci15** [comment]
Hi,

Yes, you're right: we're filtering pointers to the heap region only, which exclude pointers to allocations in regions that were mapped using `mmap()`, and only keep those allocated using `sbrk()`. JeMalloc uses `mmap()` by default, but it can be configured to use `sbrk()` instead (using the `DSS_DEFAULT ` and `DSS_PREC_DEFAULT ` macros, defined in `include/jemalloc/internal/extent_dss.h`).

We did something slightly different here instead: we use `sbrk()` for allocating space ('extents') for application allocations, but continue using `mmap()` for jemalloc's internal (metadata) allocations ("base extents").

The benefit of this is that, since we only scan the heap region (and some other regions: stack, globals), we avoid scanning jemalloc's metadata. As well as saving time, this ignores pointers from inside allocator metadata. This is the correct behaviour (and important): jemalloc keeping track of a region (or it's parent extent) should not prevent it from being returned to the allocator.

See [this commit](https://bitbucket.org/me412/jemalloc-msweeper-public/commits/c9ab8e6f0f5f1c140ed6c559c6e71113c6125485) for implementation. Its parent repository is linked to as a submodule from the `jemalloc-msweeper-public` directory of this repository.

Hope this helps,
Marton

**Comment by haozheshz** [comment]
Got it! Many thanks for your response!
